build: resolve array-bounds compiler error in xloginsert.c
Fix compilation error in polar_set_main_data function on Ubuntu 24.04.
The problem is specific to builds with newer compiler versions +
a combination of --enable-cassert, -O2 and -Werror.

The warning/error was as follows:

xloginsert.c: In function ‘polar_set_main_data’:
xloginsert.c:1364:23: error: array subscript ‘XLogRecData[0]’ is partly outside array bounds of ‘XLogRecData[0]’ [-Werror=array-bounds=]
 1364 |         mainrdata_last->next = &polar_mainrdata;
      |                       ^~
xloginsert.c:105:21: note: object ‘mainrdata_head’ of size 8
  105 | static XLogRecData *mainrdata_head;
      |                     ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Problem
The code uses an unsafe pointer casting hack to implement a dummy
head node for the linked list:
  static XLogRecData *mainrdata_head;
  static XLogRecData *mainrdata_last = (XLogRecData *) &mainrdata_head;

This treats an 8-byte pointer as if it were an entire XLogRecData struct.
When polar_set_main_data() writes to mainrdata_last->next, the compiler
detects it as an out-of-bounds write, because the object actually being
written to is just a pointer, not a full struct.

The trick is intended to avoid special-casing empty-list insertions:
mainrdata_last->next = rdata; works whether the list is empty or not,
because in the empty case it writes through the dummy node, effectively
updating mainrdata_head.

As result, insertion to the list does not need to treat insertion into
an empty list differently, assignment mainrdata_last->next = rdata works
in both cases.

There are two factors that trigger this error:
- Assertion `mainrdata_last == (XLogRecData *) &mainrdata_head` that
  lets compiler to track that assigning mainrdata_last->next actually
  modifies the mainrdata_head
- debug binaries are built with the O2 optimization level and -Werror

Solution
Change code to modify maninrdata_head explicitly.

Cherry-picked-from: ddf38c2e7f7940e96512ac7421c94d9ebcbf8031
Refs: XCOM-195