test: use proper wait_for_catchup instead of pg_sleep(1)
Using pg_sleep() as a syncronization mechanism can be flaky, depending
on I/O and CPU contention. This is probably the reason for the following
errors in the CI:

```
ERROR:  relation "t" does not exist
```
(and following pg_checksums error)

Refs: XCOM-193