test: use proper wait_for_catchup instead of pg_sleep(1)
Using pg_sleep() as a syncronization mechanism can be flaky, depending
on I/O and CPU contention. This is probably the reason for the following
errors in the CI:

```
ERROR:  relation "t" does not exist
```
(and following pg_checksums error)

Cherry-picked-from: 3211085082df364eebe9f4d868f50d39d34d0de5
Refs: XCOM-195